"""Module 4 (Weather Intelligence & Alerts) ORM models.

Two tables, mirroring the team database schema proposal (section 11):

* ``weather_events``  — one row per detected weather EVENT (not a raw report).
* ``weather_alerts``  — farmer-facing alerts derived from an event *only when*
  the weather changes what the farmer should do (the suppression principle,
  schema doc line 568).

Column lists match the schema doc exactly. Design choices follow section 18:
UUID primary keys, ``created_at`` / ``read_at`` timestamps, enums for
``severity`` / ``status``, and a JSONB ``data`` column on events for the rich
per-parameter weather facts that have no normalized home yet.

Cross-module foreign keys
-------------------------
``farmland_id`` (-> farmlands.id) and ``season_id`` (-> seasons.id) are the
central context keys (schema doc sections 16-17). Those tables are owned by
other modules (M1/M2/M3) and do not exist on this branch, so the columns are
typed as UUID *without* a DB-level ``ForeignKey`` constraint for now — adding
one would make the autogenerated migration fail (Postgres requires the
referenced table to exist). The real FK constraints are a Rule-C shared-contract
change to wire once the core/season tables land; this is tracked in
``backend/docs/m4-contract-proposal.md``. The self-referential
``weather_event_id`` FK *is* a real constraint because both tables live here.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class WeatherEvent(Base):
    """A detected weather event for a farmland.

    One row per *event* (e.g. ``heavy_rain``), never a bare weather report.
    The structured provider payload (per-parameter facts, forecast window,
    staleness, provider provenance) lives in the ``data`` JSONB column so M4
    can carry rich detail without competing with M3's normalized farm state.
    """

    __tablename__ = "weather_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    # -> farmlands.id (FK constraint deferred; see module docstring)
    farmland_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
    )
    event_type: Mapped[str] = mapped_column(String(50), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    start_time: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    end_time: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # Rich provider payload: per-parameter facts, forecast window, is_stale,
    # threshold provenance, provider metadata. JSONB so it is queryable.
    data: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    alerts: Mapped[list["WeatherAlert"]] = relationship(
        back_populates="weather_event",
        cascade="all, delete-orphan",
    )

    __table_args__ = (
        Index("ix_weather_events_farmland_id", "farmland_id"),
        Index("ix_weather_events_created_at", "created_at"),
    )


class WeatherAlert(Base):
    """A farmer-facing alert derived from a weather event.

    Created *only* when the event changes a required farmer action (suppression
    principle). ``recommended_action`` is the value-add; a bare weather report
    never becomes an alert.
    """

    __tablename__ = "weather_alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    # -> farmlands.id (FK constraint deferred; see module docstring)
    farmland_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
    )
    # -> seasons.id (FK constraint deferred; see module docstring)
    season_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )
    weather_event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("weather_events.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    recommended_action: Mapped[str | None] = mapped_column(Text, nullable=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="unread"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    read_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    weather_event: Mapped["WeatherEvent"] = relationship(back_populates="alerts")

    __table_args__ = (
        Index("ix_weather_alerts_farmland_id", "farmland_id"),
        Index("ix_weather_alerts_weather_event_id", "weather_event_id"),
        Index("ix_weather_alerts_status", "status"),
    )
