"""create initial FieldShift schema

Revision ID: 03d81c981e6b
Revises: 
Create Date: 2026-10-05 16:14:28.651144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03d81c981e6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('farmers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone_e164', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164')
    )
    op.create_table('crop_varieties',
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id', 'name', name='uq_crop_varieties_crop_name'),
    sa.UniqueConstraint('id', 'crop_id', name='uq_crop_varieties_id_crop')
    )
    op.create_table('farmer_profiles',
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('farming_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('livestock', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('farming_experience_years IS NULL OR farming_experience_years >= 0', name='ck_farmer_profiles_experience_nonnegative'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farmer_id', name='uq_farmer_profiles_farmer')
    )
    op.create_table('farmlands',
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=2), server_default=sa.text("'BD'"), nullable=False),
    sa.Column('division', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('upazila', sa.String(length=120), nullable=True),
    sa.Column('village_or_locality', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('land_area_sqm', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('land_area_display_unit', sa.String(length=24), nullable=False),
    sa.Column('soil_type', sa.String(length=120), nullable=True),
    sa.Column('irrigation_available', sa.Boolean(), nullable=True),
    sa.Column('water_source', sa.String(length=120), nullable=True),
    sa.Column('farming_method', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("land_area_display_unit IN ('square_metre', 'decimal', 'acre', 'hectare')", name='ck_farmlands_area_display_unit'),
    sa.CheckConstraint('(latitude IS NULL AND longitude IS NULL) OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)', name='ck_farmlands_coordinate_pair'),
    sa.CheckConstraint('land_area_sqm > 0', name='ck_farmlands_positive_area'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'farmer_id', name='uq_farmlands_id_farmer')
    )
    op.create_index('ix_farmlands_farmer_id', 'farmlands', ['farmer_id'], unique=False)
    op.create_table('agricultural_knowledge',
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('crop_variety_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('region_code', sa.String(length=80), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('review_status', sa.String(length=24), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status IN ('draft', 'in_review', 'approved', 'rejected')", name='ck_agricultural_knowledge_review_status'),
    sa.CheckConstraint('effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', name='ck_agricultural_knowledge_effective_dates'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['crop_variety_id', 'crop_id'], ['crop_varieties.id', 'crop_varieties.crop_id'], name='fk_agricultural_knowledge_variety_crop', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['crop_variety_id'], ['crop_varieties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['farmers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agricultural_knowledge_crop_status', 'agricultural_knowledge', ['crop_id', 'review_status'], unique=False)
    op.create_table('conversations',
    sa.Column('farmland_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmland_id', 'farmer_id'], ['farmlands.id', 'farmlands.farmer_id'], name='fk_conversations_farmland_owner', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_farmer_created', 'conversations', ['farmer_id', 'created_at'], unique=False)
    op.create_table('crop_recommendations',
    sa.Column('farmland_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('knowledge_refs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'selected', 'dismissed', 'expired')", name='ck_crop_recommendations_status'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 1)', name='ck_crop_recommendations_score_range'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmland_id'], ['farmlands.id'], name='fk_crop_recommendations_farmland', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_crop_recommendations_farmland_created', 'crop_recommendations', ['farmland_id', 'created_at'], unique=False)
    op.create_table('farmland_crop_preferences',
    sa.Column('farmland_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('preference_rank', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preference_rank > 0', name='ck_crop_preference_rank'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmland_id'], ['farmlands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('farmland_id', 'crop_id'),
    sa.UniqueConstraint('farmland_id', 'preference_rank', name='uq_crop_preference_rank')
    )
    op.create_table('seasons',
    sa.Column('farmland_id', sa.Uuid(), nullable=False),
    sa.Column('crop_id', sa.Uuid(), nullable=False),
    sa.Column('crop_variety_id', sa.Uuid(), nullable=True),
    sa.Column('variety_name', sa.String(length=160), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_growth_stage_id', sa.Uuid(), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=False),
    sa.Column('actual_yield', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('yield_unit', sa.String(length=32), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'active', 'completed', 'cancelled')", name='ck_seasons_status'),
    sa.CheckConstraint('actual_harvest_date IS NULL OR planting_date IS NULL OR actual_harvest_date >= planting_date', name='ck_seasons_harvest_after_planting'),
    sa.CheckConstraint('actual_yield IS NULL OR actual_yield >= 0', name='ck_seasons_yield_nonnegative'),
    sa.CheckConstraint('budget_amount IS NULL OR budget_amount >= 0', name='ck_seasons_budget_nonnegative'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['crop_variety_id', 'crop_id'], ['crop_varieties.id', 'crop_varieties.crop_id'], name='fk_seasons_variety_crop', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_growth_stage_id'], ['growth_stages.id'], name='fk_seasons_current_growth_stage', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['farmland_id'], ['farmlands.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'farmland_id', name='uq_seasons_id_farmland')
    )
    op.create_index('ix_seasons_crop_id', 'seasons', ['crop_id'], unique=False)
    op.create_index('ix_seasons_farmland_status', 'seasons', ['farmland_id', 'status'], unique=False)
    op.create_index('uq_seasons_one_active_per_farmland', 'seasons', ['farmland_id'], unique=True, postgresql_where="status = 'active'")
    op.create_table('weather_events',
    sa.Column('farmland_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('provider_ref', sa.String(length=200), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=24), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('end_time IS NULL OR end_time >= start_time', name='ck_weather_events_end_after_start'),
    sa.ForeignKeyConstraint(['farmland_id'], ['farmlands.id'], name='fk_weather_events_farmland', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'farmland_id', name='uq_weather_events_id_farmland')
    )
    op.create_index('ix_weather_events_farmland_start', 'weather_events', ['farmland_id', 'start_time'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=16), nullable=False),
    sa.Column('attachment_key', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("message_type IN ('text', 'image', 'system')", name='ck_chat_messages_message_type'),
    sa.CheckConstraint("sender_type IN ('farmer', 'assistant', 'system')", name='ck_chat_messages_sender_type'),
    sa.CheckConstraint('(message IS NOT NULL AND length(trim(message)) > 0) OR attachment_key IS NOT NULL', name='ck_chat_messages_content_present'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_conversation_order', 'chat_messages', ['conversation_id', 'created_at', 'id'], unique=False)
    op.create_table('disease_results',
    sa.Column('farmland_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=True),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('image_storage_key', sa.Text(), nullable=True),
    sa.Column('possible_issue', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='ck_disease_results_confidence_range'),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmland_id'], ['farmlands.id'], name='fk_disease_results_farmland', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id', 'farmland_id'], ['seasons.id', 'seasons.farmland_id'], name='fk_disease_results_season_farmland', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disease_results_farmland_created', 'disease_results', ['farmland_id', 'created_at'], unique=False)
    op.create_table('problems',
    sa.Column('farmland_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'moderate', 'high', 'critical')", name='ck_problems_severity'),
    sa.CheckConstraint("status IN ('open', 'monitoring', 'resolved', 'dismissed')", name='ck_problems_status'),
    sa.ForeignKeyConstraint(['farmland_id'], ['farmlands.id'], name='fk_problems_farmland', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id', 'farmland_id'], ['seasons.id', 'seasons.farmland_id'], name='fk_problems_season_farmland', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_problems_farmland_status_created', 'problems', ['farmland_id', 'status', 'created_at'], unique=False)
    op.create_table('season_plans',
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'superseded', 'completed')", name='ck_season_plans_status'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_season_plans_season_status', 'season_plans', ['season_id', 'status'], unique=False)
    op.create_table('weather_alerts',
    sa.Column('farmland_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=True),
    sa.Column('weather_event_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("severity IN ('low', 'moderate', 'high', 'critical')", name='ck_weather_alerts_severity'),
    sa.CheckConstraint("status IN ('new', 'read', 'actioned', 'dismissed')", name='ck_weather_alerts_status'),
    sa.ForeignKeyConstraint(['farmland_id'], ['farmlands.id'], name='fk_weather_alerts_farmland', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id', 'farmland_id'], ['seasons.id', 'seasons.farmland_id'], name='fk_weather_alerts_season_farmland', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['weather_event_id', 'farmland_id'], ['weather_events.id', 'weather_events.farmland_id'], name='fk_weather_alerts_event_farmland', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weather_alerts_farmland_status_created', 'weather_alerts', ['farmland_id', 'status', 'created_at'], unique=False)
    op.create_table('growth_stages',
    sa.Column('season_plan_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_day', sa.Integer(), nullable=True),
    sa.Column('end_day', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_day IS NULL OR start_day IS NULL OR end_day >= start_day', name='ck_growth_stages_end_day_after_start'),
    sa.CheckConstraint('sequence > 0', name='ck_growth_stages_sequence_positive'),
    sa.CheckConstraint('start_day IS NULL OR start_day >= 0', name='ck_growth_stages_start_day_nonnegative'),
    sa.ForeignKeyConstraint(['season_plan_id'], ['season_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_plan_id', 'sequence', name='uq_growth_stages_plan_sequence')
    )
    op.create_index('ix_growth_stages_plan_id', 'growth_stages', ['season_plan_id'], unique=False)
    op.create_table('farm_checkins',
    sa.Column('farmland_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=True),
    sa.Column('checkin_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('growth_stage_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('observations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['farmland_id'], ['farmlands.id'], name='fk_farm_checkins_farmland', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['growth_stage_id'], ['growth_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id', 'farmland_id'], ['seasons.id', 'seasons.farmland_id'], name='fk_farm_checkins_season_farmland', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_farm_checkins_farmland_checkin', 'farm_checkins', ['farmland_id', 'checkin_at'], unique=False)
    op.create_table('tasks',
    sa.Column('farmland_id', sa.Uuid(), nullable=False),
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('growth_stage_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high', 'urgent')", name='ck_tasks_priority'),
    sa.CheckConstraint("source IN ('season_plan', 'weather', 'disease', 'farmer', 'system')", name='ck_tasks_source'),
    sa.CheckConstraint("status IN ('pending', 'completed', 'skipped', 'cancelled')", name='ck_tasks_status'),
    sa.ForeignKeyConstraint(['growth_stage_id'], ['growth_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['season_id', 'farmland_id'], ['seasons.id', 'seasons.farmland_id'], name='fk_tasks_season_farmland', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_season_status_due', 'tasks', ['season_id', 'status', 'due_at'], unique=False)
    op.create_foreign_key(
        'fk_seasons_current_growth_stage',
        'seasons',
        'growth_stages',
        ['current_growth_stage_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_seasons_current_growth_stage',
        'seasons',
        type_='foreignkey',
    )
    op.drop_index('ix_tasks_season_status_due', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_farm_checkins_farmland_checkin', table_name='farm_checkins')
    op.drop_table('farm_checkins')
    op.drop_index('ix_growth_stages_plan_id', table_name='growth_stages')
    op.drop_table('growth_stages')
    op.drop_index('ix_weather_alerts_farmland_status_created', table_name='weather_alerts')
    op.drop_table('weather_alerts')
    op.drop_index('ix_season_plans_season_status', table_name='season_plans')
    op.drop_table('season_plans')
    op.drop_index('ix_problems_farmland_status_created', table_name='problems')
    op.drop_table('problems')
    op.drop_index('ix_disease_results_farmland_created', table_name='disease_results')
    op.drop_table('disease_results')
    op.drop_index('ix_chat_messages_conversation_order', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_weather_events_farmland_start', table_name='weather_events')
    op.drop_table('weather_events')
    op.drop_index('uq_seasons_one_active_per_farmland', table_name='seasons', postgresql_where="status = 'active'")
    op.drop_index('ix_seasons_farmland_status', table_name='seasons')
    op.drop_index('ix_seasons_crop_id', table_name='seasons')
    op.drop_table('seasons')
    op.drop_table('farmland_crop_preferences')
    op.drop_index('ix_crop_recommendations_farmland_created', table_name='crop_recommendations')
    op.drop_table('crop_recommendations')
    op.drop_index('ix_conversations_farmer_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_agricultural_knowledge_crop_status', table_name='agricultural_knowledge')
    op.drop_table('agricultural_knowledge')
    op.drop_index('ix_farmlands_farmer_id', table_name='farmlands')
    op.drop_table('farmlands')
    op.drop_table('farmer_profiles')
    op.drop_table('crop_varieties')
    op.drop_table('farmers')
    op.drop_table('crops')
    # ### end Alembic commands ###
