"""add module1 farmland and profile fields

Revision ID: 163fb0ab6beb
Revises: bd41c6a90e15
Create Date: 2026-10-07 06:42:22.229827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163fb0ab6beb'
down_revision: Union[str, Sequence[str], None] = 'bd41c6a90e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer_profiles', sa.Column('preferred_language', sa.String(length=8), server_default=sa.text("'bn'"), nullable=False))
    op.add_column('farmer_profiles', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('farmlands', sa.Column('budget_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('farmlands', sa.Column('budget_currency', sa.String(length=3), server_default=sa.text("'BDT'"), nullable=False))
    op.add_column('farmlands', sa.Column('previous_crop', sa.String(length=160), nullable=True))
    op.add_column('farmlands', sa.Column('previous_yield_amount', sa.Numeric(precision=14, scale=3), nullable=True))
    op.add_column('farmlands', sa.Column('previous_yield_unit', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmlands', 'previous_yield_unit')
    op.drop_column('farmlands', 'previous_yield_amount')
    op.drop_column('farmlands', 'previous_crop')
    op.drop_column('farmlands', 'budget_currency')
    op.drop_column('farmlands', 'budget_amount')
    op.drop_column('farmer_profiles', 'onboarding_completed_at')
    op.drop_column('farmer_profiles', 'preferred_language')
    # ### end Alembic commands ###
